### PR TITLE
Plant CI

### PR DESCRIPTION
**Pull request by lucafavatella**
Depends on #2

### CODE REVIEW

**Comment by lucafavatella** [comment]
@sylane Please see https://circleci.com/workflow-run/97dbfbf9-4658-495b-a0a3-525dbff2c7b1 (based on dfafd94) that is initial CI workflow (smoke test) I propose. Is it normal it runs for 1s? (I specified max time 1m.)

**Comment by sylane** [comment]
@lucafavatella The circleci link is 404 for me. It takes 1s with the default parameters ? This shouldn't be the case, could you post the console output ?

**Comment by sylane** [comment]
I see you do a 1 minute test, this is simulation time, no real time. One minute of simulation is really fast even more knowing that new nodes are started every 30s (simulation time).

**Comment by lucafavatella** [comment]
@dincho I tracked actually enabling CI on aeternity/aesim as https://www.pivotaltracker.com/story/show/157770816

**Comment by dincho** [comment]
Let's increase the simulation time a bit then ?

**Comment by lucafavatella** [comment]
> @lucafavatella I added the max_real_time option in #2

@sylane I rebased this PR on that. It works! Thanks.

**Comment by lucafavatella** [comment]
I rebased on master so to clarify this PR is only one commit (GitHub was showing 2).

> Let's increase the simulation time a bit then ? I guess CI runtime of ~1min is still very fast.

@dincho I believe this is addressed now.

**Pull request merged**
